import jsPDF from 'jspdf';

/**
 * Export text/markdown content as a PDF file
 */
export function exportContentAsPdf(title: string, content: string, metadata?: {
  category?: string;
  author?: string;
  date?: string;
  tags?: string[];
}) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  // Header
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text('UHS Health OS', margin, y);
  if (metadata?.date) {
    doc.text(metadata.date, pageWidth - margin, y, { align: 'right' });
  }
  y += 8;

  // Title
  doc.setFontSize(18);
  doc.setTextColor(30, 30, 30);
  const titleLines = doc.splitTextToSize(title, maxWidth);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 8 + 4;

  // Metadata line
  if (metadata?.category || metadata?.tags?.length) {
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    const parts: string[] = [];
    if (metadata.category) parts.push(metadata.category);
    if (metadata.tags?.length) parts.push(metadata.tags.join(', '));
    doc.text(parts.join(' | '), margin, y);
    y += 6;
  }

  // Separator line
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Content - strip markdown syntax for cleaner PDF
  const cleanContent = content
    .replace(/^#{1,6}\s+(.+)$/gm, '$1') // headers
    .replace(/\*\*(.+?)\*\*/g, '$1') // bold
    .replace(/\*(.+?)\*/g, '$1') // italic
    .replace(/`(.+?)`/g, '$1') // inline code
    .replace(/^\s*[-*+]\s+/gm, '• ') // list items
    .replace(/^\s*\d+\.\s+/gm, '') // numbered list markers
    .replace(/\[(.+?)\]\(.+?\)/g, '$1') // links
    .replace(/^>\s+/gm, '  ') // blockquotes
    .replace(/```[\s\S]*?```/g, '') // code blocks
    .replace(/\n{3,}/g, '\n\n'); // excessive newlines

  doc.setFontSize(11);
  doc.setTextColor(40, 40, 40);

  const paragraphs = cleanContent.split('\n');

  for (const paragraph of paragraphs) {
    const trimmed = paragraph.trim();
    if (!trimmed) {
      y += 4;
      continue;
    }

    const lines = doc.splitTextToSize(trimmed, maxWidth);

    // Check if we need a new page
    const blockHeight = lines.length * 5.5;
    if (y + blockHeight > pageHeight - margin) {
      doc.addPage();
      y = margin;
      // Page header
      doc.setFontSize(8);
      doc.setTextColor(160, 160, 160);
      doc.text(title, margin, y);
      y += 8;
      doc.setFontSize(11);
      doc.setTextColor(40, 40, 40);
    }

    doc.text(lines, margin, y);
    y += blockHeight + 2;
  }

  // Footer on last page
  doc.setFontSize(8);
  doc.setTextColor(160, 160, 160);
  doc.text(
    'Generated by UHS Health OS — For educational purposes only',
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  );

  doc.save(`${title.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 50)}.pdf`);
}
