[package]
name = "urv-privacy"
version = "0.1.0"
description = "URV Health Value Chain - Privacy-preserving on-chain proof registry"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "urv_privacy"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
