// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Projeto Rheuma — banco oficial da aplicação.
// Qualquer ambiente (Lovable, Vercel, local) usa este projeto.
const SUPABASE_URL = 'https://jiswutjmmoirkoarpbpf.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imppc3d1dGptbW9pcmtvYXJwYnBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcwODEwMjksImV4cCI6MjA5MjY1NzAyOX0.JLoRHQsI0AEr4KpWA2-e4gapSrGqYf5IZ3J5P8Vdnuo';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});