- uses: cloudflare/wrangler-action@v3
  with:
    apiToken: *** accountId: *** command: pages deploy dist --project-name=rhema-care-flow --branch=pr-45
    quiet: false
    # Força a instalação da versão mais recente que corrige o bug
    wranglerVersion: '4'
    
